### ISSUE TITLE
Aborted job queue due to an unexpected runtime error.

### ISSUE THREAD

**Issue by thewerd** [mynttt/PlexImdbUpdateTool#1]
This went through fine for a bunch of movies, then failed with this error. I am sure it is a naming of it or something, but I can't seem to identify which movie it failed at. Let me know if there's any other information I can supply.

Aborted job queue due to an unexpected runtime error. Please send this to the maintainer of the application if you wish to file a bug report.

java.lang.NumberFormatException: For input string: "N/A"
        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
        at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.base/java.lang.Double.parseDouble(Double.java:543)
        at ImdbUpdater.Utility.updateMetadata(Utility.java:66)
        at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1746)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at ImdbUpdater.JobRunner.transformMeta(JobRunner.java:298)
        at ImdbUpdater.JobRunner.jobInternal(JobRunner.java:187)
        at ImdbUpdater.JobRunner.run(JobRunner.java:173)
        at ImdbUpdater.Main.runJobs(Main.java:144)
        at ImdbUpdater.Main.main(Main.java:107)

The progress has been saved.

======[ class java.lang.NumberFormatException ]======

**Comment by mynttt** [comment]
Looks like this is the OMDB way of saying that no rating exists. OMDB supplies the ratings as strings but the database takes them as decimal numbers. The conversion failed here as "N/A" is not a decimal number.

I will add a condition that loggs that the OMDB response has no rating and causes this tool to not enforce any update since it has no data to work with.

Thanks for reporting this!

**Comment by mynttt** [comment]
Has been fixed by [1.0.3](https://github.com/mynttt/PlexImdbUpdateTool/releases/tag/1.0.3). It will now ignore these edge cases and print a warning that the movie was ignored due to the rating missing.
